In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))


TensorFlow version: 2.19.0
Num GPUs Available: 0


In [2]:
tf.random.normal([1000, 1000])

<tf.Tensor: shape=(1000, 1000), dtype=float32, numpy=
array([[-1.9086347 ,  0.38569018,  0.3939514 , ..., -1.3492421 ,
        -0.14995337,  1.8479543 ],
       [-2.704023  , -0.23299357, -0.34921902, ..., -2.7263563 ,
        -1.4156519 , -0.2750969 ],
       [ 0.66528493,  0.25742936,  1.0470332 , ..., -0.04957503,
         2.3853889 ,  1.005654  ],
       ...,
       [ 0.67586046,  0.8331853 ,  1.3329499 , ..., -2.3916984 ,
        -0.6016305 , -0.9886505 ],
       [-0.62684983, -0.99799734,  1.5005652 , ..., -1.787807  ,
         0.19332606,  0.01843349],
       [-1.5841534 , -0.10678286,  0.25737658, ..., -0.79401195,
         1.0119832 ,  0.8233317 ]], dtype=float32)>

In [3]:
result = tf.reduce_sum(tf.random.normal([1000, 1000]))
print(result)

tf.Tensor(-73.35928, shape=(), dtype=float32)


In [4]:
from tensorflow import keras
from keras import datasets

In [5]:
(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()
train_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
#
# Check the dataset loaded
#
train_images.shape, test_images.shape

((60000, 28, 28), (10000, 28, 28))

In [8]:
# 4. Test program for PyTorch

import torch
import torch.nn as nn

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())


PyTorch version: 2.3.1+cpu
CUDA available: False
